### ISSUE TITLE
I cannot open DevTools in musixmatch

### ISSUE THREAD

**Issue by Disgame** [khanhas/genius-spicetify#10]
I tried it for over 10 minutes but couldn't figure out what to do to fix it.

I have reinstalled the program but it doesn't work.

**Comment by khanhas** [comment]
How did you install Musixmatch?
Only version on Windows Store are able to open DevTool

**Comment by Disgame** [comment]
Oh now it worked. I'll close the issue. 
Thanks for your reponse !

**Comment by dotrachit** [comment]
> How did you install Musixmatch?
> Only version on Windows Store are able to open DevTool

@khanhas is there any workaround for mac users?

**Comment by chen-siyuan** [comment]
@rchtgpt same issue here. is there a way to get the token for mac users?

**Comment by rchtgpt** [comment]
@chen-siyuan I realised that I didn't really need a musixmatch token because the lyrics section was there when I installed spicetify.

Only difference is that you need to click the lyrics icon on the LHS and not the one at the bottom.

<img width="1847" alt="image" src="https://user-images.githubusercontent.com/44428198/110077008-758d3480-7dab-11eb-9f27-e88a484d92c7.png">
